{
  "hash": "d93312ebfedbce997eda9f0365259cec",
  "result": {
    "markdown": "---\ntitle: \"Data transformation\"\n---\n\n\nThis exercise examines how income inequality has changed over time in the U.S. We will measure inequality by the 10th, 50th, and 90th percentiles of wage and salary income from 1962 to 2022. We expect that this exercise may take more time than one discussion session.^[Thanks to past TA Abby Sachar for designing the base of this exercise.] You will begin by downloading data and end by making this graph.\n\n\n::: {.cell}\n\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](data_transformation_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n## Data access\n\nThis exercise uses data from the Current Population Survey.\n\n1. Register for an account at [cps.ipums.org](https://cps.ipums.org/cps/)\n2. Log in\n3. Click \"Get Data\"\n4. Add the following variables to your cart: [`incwage`](https://cps.ipums.org/cps-action/variables/incwage), [`educ`](https://cps.ipums.org/cps-action/variables/educ), [`wkswork2`](https://cps.ipums.org/cps-action/variables/wkswork2), [`age`](https://cps.ipums.org/cps-action/variables/age), [`asecwt`](https://cps.ipums.org/cps-action/variables/asecwt)\n5. Add the 1962--2023 ASEC samples to your cart. Exclude the basic monthly samples\n6. Create a data extract\n\t- Select cases to only download people ages 30--45\n\t- Choose to download in Stata (.dta) format\n7. Submit your extract and download the data!\n\nStore your data in a **working directory**: a folder on your computer that will hold the data for this exercise.\n\n::: {.callout-tip}\nKeep a browser tab open with the [IPUMS webpage](https://cps.ipums.org) to easily access full documentation\n:::\n\n\n{{< video https://www.youtube.com/embed/JTsFJtlLOrY >}}\n\n\n  \n## Prepare R environment\n\nIn RStudio, create a Quarto document. Save it in your working directory.\n\nUse the code below to load packages:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(haven)\n```\n:::\n\n\nThe [`haven`](https://haven.tidyverse.org/) package allows us to load data in the `.dta` format designed for Stata. Use [`read_dta()`](https://haven.tidyverse.org/reference/read_dta.html)) and store the data in an object called `micro`. By default, these data are stored in a [`tibble`](https://tibble.tidyverse.org/).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicro <- read_dta(\"cps_00077.dta\")\n```\n:::\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-tip}\n- Change the file name to the name of the file you downloaded\n- If R says the file does not exist in your current working directory, you may need to [set your working directory](https://support.posit.co/hc/en-us/articles/200711843-Working-Directories-and-Workspaces-in-the-RStudio-IDE) by clicking Session -> Set Working Directory -> To Source File Location on a Mac or Tools -> Change Working Directory on Windows.\n:::\n\n\n{{< video https://www.youtube.com/embed/LjO15pvVmNg >}}\n\n\n\n## Get familiar with our dataset\n\nType `micro` in the console. What do you see?\n\n- How many rows are there?\n- How many columns?\n\nSome columns such as [`educ`](https://cps.ipums.org/cps-action/variables/educ#codes_section) have a numeric code and a label. The code is how IPUMS has stored the data. The label is what the code means. Getting these labels is a benefit of downloading the file in `.dta` format.\n\nType `View(micro)` in the console. This will pop up another tab in RStudio which allows you to scroll through the dataset. You can see that each column name has a description. For instance [`asecwt`](https://cps.ipums.org/cps-action/variables/asecwt) is \"annual social and economic supplement weight.\"\n\n\n{{< video https://www.youtube.com/embed/f9IeokvW8HM >}}\n\n\n\n## filter() to cases of interest\n\n> In this step, you will use [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) to convert your `micro` object\nto a new object called `filtered`.\n\nThe [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) function keeps only rows in our dataset that correspond to those we want to study. The [examples](https://dplyr.tidyverse.org/reference/filter.html#ref-examples) on the documentation page are especially helpful. The [R4DS section](https://r4ds.hadley.nz/data-transform#filter) is also helpful.\n\nHere are two ways to use [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) to restrict to people working 50+ weeks per year. One way is to call the `filter()` function and hand it two arguments\n\n- `.data = micro` is the dataset\n- `year == 1962` is a logical condition coded `TRUE` for observations in 1962\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfilter(.data = micro, year == 1962)\n```\n:::\n\n\nThe result of this call is a [`tibble`](https://tibble.tidyverse.org/) with only the observations from 1962. Another way to do the same operation is with the pipe operator `|>`\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicro |>\n  filter(year == 1962)\n```\n:::\n\n\nThis approach begins with the data set `micro`. The pipe operator `|>` hands this data set on as the first argument to the [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) function in the next line. As before, the second argument is the logical condition `year == 1962`.\n\nThe piping approach is often preferable because it reads like a sentence: begin with data, then filter to cases with a given condition. The pipe is also useful \n\nThe pipe operator `|>` takes what is on the first line and hands it on as the first argument to the function in the next line. This reads in a sentence: begin with the `micro` tibble and then [`filter()`](https://dplyr.tidyverse.org/reference/filter.html) to cases with `year == 1962`. The pipe can also string together many operations, with comments allowed between them:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmicro |>\n  # Restrict to 1962\n  filter(year == 1962) |>\n  # Restrict to ages 40-44\n  filter(age >= 40 & age <= 44)\n```\n:::\n\n\n**Your turn.** Begin with the `micro` dataset. Filter to\n\n- people working 50+ weeks per year (check documentation for [`wkswork2`](https://cps.ipums.org/cps-action/variables/WKSWORK2#codes_section)) \n- valid report of [`incwage`](https://cps.ipums.org/cps-action/variables/INCWAGE) greater than 0 and less than 99999998\n\n\n::: {.cell}\n\n:::\n\n\nIf you get stuck, see how we did it at the [end of this page](#all-together). `filtered` should have 1,350,542 rows and 15 columns.\n\n::: {.callout-note}\nFiltering can be a dangerous business! For example, above we dropped people with missing values of income. But what if the lowest-income people refuse to answer the income question? We often have no choice but to filter to those with valid responses, but you should always read the documentation to be sure you understand who you are dropping and why.\n:::\n\n::: columns\n::: {.column width=\"50%\"}\n\n#### filter() without the pipe\n\n{{< video https://www.youtube.com/embed/mbnFNwuQbCM >}}\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n#### filter() with the pipe\n\n{{< video https://www.youtube.com/embed/OtBEsiaTnYQ >}}\n\n\n:::\n:::\n\n## group_by() and summarize() for subpopulation summaries\n\n> In this step, you will use `group_by()` and `summarize()` to convert your `mutated` object to a new object called `summarized`.\n\nEach row in our dataset is a person. We want a dataset where each row is a year.\n\n- Use `group_by()` function to group by `year`. The next operations will automatically be carried out within groups\n- Use `summarize()` to aggregate to the 10th, 50th, and 90th percentiles within each year\n     - `p10 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.1)`\n     - `p50 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.5)`\n     - `p90 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.9)`\n     \nIf you get stuck, see how we did it at the [end of this page](#all-together).\n     \n::: {.callout-tip}\nThat was a new way of calling a package! The [`Hmisc`](https://cran.r-project.org/web/packages/Hmisc/index.html) package has a bunch of miscellaneous functions. To install the package, type `install.packages(\"Hmisc\")`. One of the functions is `wtd.quantile()`, which summarizes data with weighted quantiles (e.g., the 10th percentile estimated in a survey with sampling weights). So why call it with `Hmisc::wtd.quantile()` instead of using `library(Hmisc)`? When you use `library()`, you load all the functions in a package. `Hmisc` is a big package, and some of the functions have the same names as other functions we use in `tidyverse`. Loading the whole package can create conflicts where two function shave the same name! Instead, the way we've written it above tells R to just look in the package for the particular function we're using at that moment.\n:::\n\n\n::: {.cell}\n\n:::\n\n\n::: {.callout-note}\nThe `summarized` data frame should have 62 rows and 4 columns (year, education categories, p10, p50, and p90).\n:::\n\n::: columns\n::: {.column width=\"50%\"}\n\n#### Sample summaries\n\n{{< video https://www.youtube.com/embed/s7g0bcmtarA >}}\n\n\n:::\n\n::: {.column width=\"50%\"}\n\n#### Weighted sample summaries\n\n{{< video https://www.youtube.com/embed/7cAZjqEmsaY >}}\n\n\n:::\n:::\n\n## pivot_longer() to reshape data\n\n> In this step, you will use `pivot_longer()` to convert your `summarized` object to a new object called `pivoted`. We first explain why, then explain the task.\n\nWe ultimately want to make a `ggplot()` where income values are placed on the y-axis. We want to plot the 10th, 50th, and 90th percentiles along this axis, distinguished by color. We need them all in one colun! But currently, they are in three columns.\n\nHere is the task. How our data look:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 62 × 4\n   year   p10   p50   p90\n  <dbl> <dbl> <dbl> <dbl>\n1  1962  2000  5100  9000\n2  1963  2000  5200  9200\n# ℹ 60 more rows\n```\n:::\n:::\n\n    \nHere we want our data to look:\n\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 186 × 3\n   year quantity income\n  <dbl> <chr>     <dbl>\n1  1962 p10        2000\n2  1962 p50        5100\n3  1962 p90        9000\n4  1963 p10        2000\n5  1963 p50        5200\n6  1963 p90        9200\n# ℹ 180 more rows\n```\n:::\n:::\n\n\nThis way, we can use `year` for the x-axis, `quantity` for color, and `value` for the y-axis.\n\nUse [`pivot_longer()`](https://tidyr.tidyverse.org/reference/pivot_longer.html) to change the first data frame to the second.\n\n- Use the `cols` argument to tell it which columns will disappear\n- Use the `names_to` argument to tell R that the names of those\n  variables will be moved to a column called `quantity`\n- Use the `values_to` argument to tell R that the values of those\n  variables will be moved to a column called `income`\n  \nIf you get stuck, see how we did it at the [end of this page](#all-together).\n\n\n::: {.cell}\n\n:::\n\n{{< video https://www.youtube.com/embed/v5QJaMjO53o >}}\n\n\n\n## left_join() an inflation adjustment\n\n> In this step, you will use [`left_join()`](https://r4ds.hadley.nz/joins#sec-mutating-joins) to merge in an inflation adjustment\n\nA dollar in 1962 bought a lot more than a dollar in 2022. We will adjust for inflation using the [Consumer Price Index](https://www.bls.gov/cpi/), which tracks the cost of a standard basket of market goods. We already took this index to create a file [`inflation.csv`](../data/inflation.csv),\n\n\n::: {.cell}\n\n```{.r .cell-code}\ninflation <- read_csv(\"https://info3370.github.io/data/inflation.csv\")\n```\n:::\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 62 × 2\n   year inflation_factor\n  <dbl>            <dbl>\n1  1962            10.1 \n2  1963             9.95\n3  1964             9.82\n# ℹ 59 more rows\n```\n:::\n:::\n\n\nThe `inflation_factor` tells us that \\$1 in 1962 could buy about as much as \\$10.10 in 2023. To take a 1962 income and report it in 2023 dollars, we should multiple it by 10.1. We need to join our data\n\n::: {.cell}\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 186 × 3\n   year quantity income\n  <dbl> <chr>     <dbl>\n1  1962 p10        2000\n2  1962 p50        5100\n3  1962 p90        9000\n# ℹ 183 more rows\n```\n:::\n:::\n\ntogether with `inflation.csv` by the linking variable `year`. Use [`left_join()`](https://r4ds.hadley.nz/joins#sec-mutating-joins) to merge `inflation_factor` onto the dataset `pivoted`. Below is a hypothetical example for the structure.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hypothetical example\njoined <- data_A |>\n  left_join(\n    data_B,\n    by = join_by(key_variable_in_A_and_B)\n  )\n```\n:::\n\n\nIf you get stuck, see how we did it at the [end of this page](#all-together).\n\n::: {.cell}\n\n:::\n\n{{< video https://www.youtube.com/embed/gKnG8nSc-Go >}}\n\n\n\n## mutate() to adjust for inflation\n\n> In this step, you will use [`mutate()`](https://r4ds.hadley.nz/data-transform#sec-mutate) to multiple `income` by the `inflation_factor`\n\nThe [`mutate()`](https://r4ds.hadley.nz/data-transform#sec-mutate) function modifies columns. It can overwrite existing columns or create new columns at the right of the data set. The new variable is some transformation of the old variables.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Hypothetical example\nold_data |>\n  mutate(new_variable = old_variable_1 + old_variable_2)\n```\n:::\n\n\nUse [`mutate()`](https://r4ds.hadley.nz/data-transform#sec-mutate) to modify `income` so that it takes the values `income * inflation_factor`. If you get stuck, see how we did it at the [end of this page](#all-together).\n\n\n::: {.cell}\n\n:::\n\n{{< video https://www.youtube.com/embed/1RAMjEcqsT4 >}}\n\n\n\n## ggplot() to visualize\n\nNow make a `ggplot()` where\n\n- `year` is on the x-axis\n- `income` is on the y-axis\n- `quantity` is denoted by color\n\nDiscuss. What do you see in this plot?\n\n\n\n\n{{< video https://www.youtube.com/embed/QI6TdgrxyXo >}}\n\n\n\n## All together\n\nPutting it all together, we have a pipeline that goes from data to the plot.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nread_dta(\"cps_00077.dta\") |>\n  # Subset to cases working full year\n  filter(wkswork2 == 6) |>\n  # Subset to cases with valid income\n  filter(incwage > 0 & incwage < 99999998) |>\n  # Produce summaries\n  group_by(year) |>\n  summarize(\n    p10 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.1),\n    p50 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.5),\n    p90 = Hmisc::wtd.quantile(x = incwage, weights = asecwt, probs = 0.9\n    ),\n    .groups = \"drop\"\n  ) |>\n  pivot_longer(\n    cols = c(\"p10\",\"p50\",\"p90\"),\n    names_to = \"quantity\",\n    values_to = \"income\"\n  ) |>\n  # Join data for inflation adjustment\n  left_join(\n    read_csv(\"inflation.csv\"),\n    by = join_by(year)\n  ) |>\n  # Apply the inflation adjustment\n  mutate(income = income * inflation_factor) |>\n  # Produce a ggplot\n  ggplot(aes(x = year, y = income, color = quantity)) +\n  geom_line() +\n  xlab(\"Year\") +\n  scale_y_continuous(name = \"Annual Wage and Salary Income\\n(2023 dollars)\",\n                     labels = scales::label_dollar()) +\n  scale_color_discrete(name = \"Percentile of\\nDistribution\",\n                       labels = function(x) paste0(gsub(\"p\",\"\",x),\"th\")) +\n  theme(axis.text.x = element_text(angle = 45, hjust = 1))\n```\n:::\n\n\n## Finished early?\n\nIf you are finished early, you could\n\n- incorporate the [`educ`](https://cps.ipums.org/cps-action/variables/educ#codes_section) variable in your plot. You might want to group by those who do and do not hold college degrees, perhaps using [`facet_grid()`](https://ggplot2.tidyverse.org/reference/facet_grid.html)\n- try [`geom_histogram()`](https://ggplot2.tidyverse.org/reference/geom_histogram.html) for people's incomes in a specific year\n- explore [IPUMS-CPS](https://cps.ipums.org/) for other variables and begin your own visualization\n\n\n",
    "supporting": [
      "data_transformation_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}