project:
  type: website
  render: 
    - "*.qmd"
    - "!/assets/"

execute: 
  freeze: auto

website:
  title: "Studying Social Inequality with Data Science"
  description: "Generate new knowledge about social inequality using the tools of data science."
  navbar:
    pinned: true
    right:
      - href: index.qmd
        text: " "
      - href: assets/syllabus.pdf
        text: Syllabus
      - href: who_we_are.qmd
        text: Team
      - href: due_dates.qmd
        text: Due Dates
      - href: office_hours.qmd
        text: Office Hours
      - href: "https://edstem.org/us/courses/54550/"
        text: Ed Discussion
  sidebar:
    style: "docked"
    search: true
    collapse-level: 2
    contents:
      - href: index.qmd
        text: Home
      - section: "Topics"
        contents:
          - topics/welcome.qmd
          - section: "Generating Data"
            contents:
              - topics/surveys.qmd
              - topics/sampling.qmd
          - section: "Working with Data"
            contents:
              - topics/r_basics.qmd
              - topics/visualization.qmd
              - topics/data_transformation.qmd
          - section: "Describing inequality"
            contents:
              - topics/race.qmd
              - topics/gender.qmd
              - topics/class.qmd
          - topics/asking_questions.qmd
          - section: "Reducing inequality"
      - section: "Assignments"
        contents:
          - section: "Problem Sets"
            contents:
              - href: assignments/pset0.qmd
                text: "Problem Set 0"
          - href: assignments/project.qmd
            text: "Project"
              
  back-to-top-navigation: true

format:
  html:
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    # grid: 
    #   sidebar-width: 300px



