---
title: "Problem Set 5: Moral Arguments + Project Planning"
format: pdf
---

**Due: 5pm on Wednesday, April 17.**

Student identifer: [type your anonymous identifier here]

- Use this .qmd template to complete the problem set
- In Canvas, you will upload the PDF produced by your .qmd file
- Put your identifier above, not your name! We want anonymous grading to be possible

# 1. Objective and Normative Claims

For 1.1--1.4, tell us whether each claim is objective or normative. No explanation necessary; your answer can be the word "objective" or "normative."

**1.1 (2 points)** Most Americans believe the government should provide free primary education to all children.

**1.2 (2 points)** The government should provide free primary education to all children.

**1.3 (2 points)** The Black-white wealth gap in the U.S. is too large.

**1.4 (2 points)** Across U.S. households in 2022, the median white household held \$5.48 of net worth for each \$1 held by the median Black household.

# 2. Applying Rawls

For 2.1 and 2.2, argue for the claim using ideas from Rawls. Your answer might be a couple of sentences.

**2.1 (6 points)** Claim: A just society would be structured so that everyone would be guaranteed a basic standard of living that includes housing, basic food needs, and health care.

**2.2 (6 points)** Claim: It might be just to pay medical doctors a higher hourly wage than the median worker.

# 3. Project Planning

The following questions are about your group's plan for the final project. Answers will be longer for those in graduate groups because you will want to tell us about all of your visualizations. Some answers (e.g., the unit of analysis) might be the same for all of your visualizations while others (e.g., the predictors) might be different.

**3.1 (5 points)** What is the research question in one sentence? Grad students may use up to 3 sentences.

**3.2 (5 points)** What is the unit of analysis?

**3.3 (5 points)** What is your target population?

**3.4 (5 points)** What are the predictor(s) or population subgroup(s) you will study?

**3.5 (5 points)** What is the outcome variable?

**3.6 (5 points)** What summary statistic (e.g., mean or median) will you use to aggregate the outcome variable?

**Note to grad students:** In this problem set, the graduate work is embedded within the main problem set, because your project (Problem 3) is simply more extensive. We will calculate your score on the graduate assignment as follows: we will take your score out of 30 on Problem 3, multiply by 2/3, and enter this as your score out of 20 on the graduate assignment.