---
title: "Moral Arugments"
---

Most of this course uses data to describe objective facts about inequality. This lecture takes a departure into philosophy about normative claims about what we should want, and about how inequality might or might not be morally justified. We will engage with two philosophers: John Rawls and Robert Nozick.

## Rawls: Justice as fairness

[[Slides on Rawls]](../slides/lec10/rawls.pdf)

*A Theory of Justice* was a landmark work of political philosophy written by John Rawls in 1971. You might watch this [quick video](https://www.youtube.com/watch?v=5-JQ17X6VNg) introducing the key points of this perspective.

Rawls advocates a procedural definition of justice: a just distribution is one that would be chosen under a fair procedure.

His proposed fair procedure is one in which none of us knows our own place within society---a setting he calls the **original position**. The original position formalizes the notion that whether a distribution is just should not depend on my own position within that distribution.

From the original position, Rawls argues that we would choose two principles of justice

1. **Equality of liberty:** "each person is to have an equal right to the most extensive basic liberty compatible with a similar liberty for others" (p. 60)
2. **Difference principle:** "social and economic inequalities are to be arranged so that they are both
     a. reasonably expected to be to everyone's advantage and
     b. attached to positions and offices open to all" (p. 60)

{{< video https://www.youtube.com/embed/HIfGT-6C5bU >}}

## Nozick: Justice as individual rights

[[Slides on Nozick]](../slides/lec10/nozick.pdf)

You might watch 3:49--5:05 of [this video](https://youtu.be/H0CTHVCkm90?t=229) introducing a key example from Nozick's argument.

In *Anarchy, State, and Utopia*, Robert Nozick argues that

1. a minimal state is justified
2. no more exensive state is justified

Thus, for Nozick the government has no justifiable role in redistributing income or wealth to achieve some desired distribution. For Nozick, any distribution is just if it arises via

1. just acquisition of holdings
2. just transfers of holdings

We will discuss Nozick's argument for libertarian government. We will also discuss how one could justify government redistribution within Nozick's framework, in cases where (1) and (2) are violated in the historical process that produced current holdings.

{{< video https://www.youtube.com/embed/5U6qg8dcQVA >}}

## Application: Reparations

[[Slides on reparations]](../slides/lec11/reparations.pdf)

Finally, we discussed reparations to correct past injustice as a case study to apply ideas from Rawls and Nozick.
